services:
  streams:
    build: .
    depends_on:
      - broker
      - schema-registry
    environment:
      KAFKA_BOOTSTRAP_SERVERS: broker:29092
      APPLICATION_ID: "word-count-app"
      STORE_NAME: "counts-store"
      KAFKA_METRICS_RECORDING_LEVEL: "DEBUG"
      JAVA_OPTS: -javaagent:/usr/share/jmx_exporter/jmx_prometheus_javaagent-0.14.0.jar=1234:/usr/share/jmx_exporter/kafka-streams-post-2.5.yml -Xmx256M -Xms256M
    volumes:
      - ../jmx-exporter:/usr/share/jmx_exporter/
